import Head from 'next/head'

import { MainContext } from '@/state'
import { initialState } from '@/state'
import { mainReducer } from '@/state/reducer'
import { useReducer } from 'react'

import MainLayout from '@/layouts/MainLayout'
import Todo from '@/components/Todo'

import styles from '@/styles/Home.module.css'


export default function Home() {
  
  
  const [state , dispatch]= useReducer(mainReducer, initialState)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <MainContext.Provider value={{state , dispatch}}>
        <MainLayout>
          <Todo/>
        </MainLayout>
      </MainContext.Provider>
      
    </>
  )
}
