import Head from "next/head";

import { MainContext } from "@/state";
import { initialState } from "@/state";
import { mainReducer } from "@/state/reducer";
import { useContext, useLayoutEffect, useReducer } from "react";
import { db } from "../plugins/firebase";
import { collection, getDocs } from "firebase/firestore";

import MainLayout from "@/layouts/MainLayout";
import Todo from "@/components/Todo";

import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Navbar from "@/components/Navbar";

export default function Home({ data }) {
  useLayoutEffect(() => {
    dispatch({ type: "SET_DATABASE", payload: data });
  }, []);

  const { state, dispatch } = useContext(MainContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainLayout />

      {state.username ? (
        <Todo />
      ) : (
        <div className={styles.login}>
          <h1>Per favore autenticarsi</h1>
          <Link href="/login">Login</Link>
        </div>
      )}
    </>
  );
}

export async function getServerSideProps(context) {
  const data = [];
  const querySnapshot = await getDocs(collection(db, "TodoList"));

  querySnapshot.forEach((doc) => {
    data.push({ ...doc.data(), id: doc.id });
  });

  return {
    props: {
      data,
    },
  };
}
